WIP color changes for y6
esheldon/meds pull request #52
Opened 2021-11-18 18:16 UTC by beckermr

This PR has changes for Y6 color dependence in our data products.

2022-10-13 19:26 UTC, esheldon requested changes

2022-10-13 19:26 UTC, esheldon commented on meds/maker.py
> +        except TypeError:
if the user sent colors but the function doesn't accept colors, we should be crashing.

2022-10-13 19:26 UTC, esheldon commented on meds/maker.py
> +                    except TypeError:
Here also we should not allow this

2022-10-13 19:26 UTC, esheldon commented on meds/maker.py
> +                except TypeError:
and here

2022-10-14 11:21 UTC, beckermr commented on meds/maker.py
> +
I changed the TypeError handling per your request. Note that I was following the pattern here in the WCS handling. I've changed that pattern here too.

2022-10-14 11:39 UTC, beckermr commented
Ahhhhh, we have to keep the try except blocks because the coadd quantities don't always accept a color but we pass it anyways.

2022-10-17 13:21 UTC, beckermr commented
bump here @esheldon

2022-10-17 13:27 UTC, esheldon commented
> Ahhhhh, we have to keep the try except blocks because the coadd quantities don't always accept a color but we pass it anyways.

I think the right thing to do would be to identify when that situation occurs and deal with it separately, to avoid user error in this case.

If you think this is just not worth it, I will accept your judgement.

2022-10-17 13:28 UTC, esheldon reviewed
See comment in conversation thread

2022-10-17 17:00 UTC, beckermr commented
OK @esheldon ready for another look!

2022-10-17 17:04 UTC, esheldon approved these changes

2022-10-20 14:55 UTC, merged